### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by hthanhdev** [hthanhdev/form#1]
# **Features**
- [ ] Detect permission fields
- [ ]  ..... 

# **Others**
- [ ] Code documents. typedoc
- [ ]  API documents
- [ ]  Benchmark
- [ ]  Test coverage report
